# HomotopyContinuation 

We wish to replicate the [Duffing equation demo](https://discourse.julialang.org/t/bifurcationkit-duffing-equation-time-harmonic-single-harmonic/123937) using homotopycontinuation. 

See [homotopycontinuation](https://www.juliahomotopycontinuation.org/) for documentation. 

In [20]:
using HomotopyContinuation

using Plots 

## Section 1: Introduction

More later.

## Section 2: Tutorial Example

We reproduce the example at [guides/many-systems](https://www.juliahomotopycontinuation.org/guides/many-systems/). 

### Section 2.1: Single Parameter Solve 

In [4]:
@var x y z p[1:3]

F = System(
    [
        x + 3 + 2y + 2y^2 - p[1],
        (x - 2 + 5y) * z + 4 - p[2] * z,
        (x + 2 + 4y) * z + 5 - p[3] * z,
    ];
    parameters = p
)

System of length 3
 3 variables: x, y, z
 3 parameters: p₁, p₂, p₃

 3 - p₁ + x + 2*y + 2*y^2
 4 - z*p₂ + z*(-2 + x + 5*y)
 5 - z*p₃ + z*(2 + x + 4*y)

In [5]:
# Generate generic parameters by sampling complex numbers from the normal distribution
p₀ = randn(ComplexF64, 3)
# Compute all solutions for F_p₀
result_p₀ = solve(F, target_parameters = p₀)

Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xc199d986
• start_system: :polyhedral


In [62]:
typeof(result_p₀)

Result

### Section 2.2: Repeated Parameter Values 

In [6]:
# generate some random data to simulate the parameters
data = [randn(3) for _ in 1:10_000]

# track p₀ towards the entries of data
data_points = solve(
    F,
    solutions(result_p₀);
    start_parameters =  p₀,
    target_parameters = data
)

10000-element Vector{Tuple{Result, Vector{Float64}}}:
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xb4ede105
, [-0.7540106520965347, 0.8452056735243576, -2.299342643804846])
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xb4ede105
, [0.1903132880054627, -1.2449042295235746, 1.0295128356543122])
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xb4ede105
, [0.4324953699608858, 0.06186768681791865, -0.8197592825930693])
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xb4ede105
, [-0.09699238383299766, 0.25654872230303594, 0.568256692611777])
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• random_seed: 0xb4ede105
, [-0.009001827721125094, 0.8160999735234854, 1.1085668413558807])
 (Result with 2 solutions
• 2 paths tracked
• 2 non-singular solutions (0 real)
• rando

## Section 3: Linear Harmonic Oscillator 

In [9]:
function  duffing_hb_singlemode(x,p)
    A, B = x 
    omd = p 
    m=1; freq = .5; om0=2*π*freq; ga=0.1; stiffnlin=10.; F0 = 1.; 
    mismathvec = zeros(eltype(x),2)
    mismathvec[1] = m*(om0^2-omd^2)*A + ga*omd*B + stiffnlin*.75*(A^3 + A*B^2) 
    mismathvec[2] = -ga*omd*A + m*(om0^2-omd^2)*B + stiffnlin*.75*(B^3 + A^2*B) - F0 
    return mismathvec 
end 

duffing_hb_singlemode (generic function with 1 method)

In [7]:
# define sytem - version 1
# p declared as a scalar  
@var A B p

m=1; freq = .5; om0=2*π*freq; ga=0.1; F0 = 1.;

F = System(
    [
        m*(om0^2-p[1]^2)*A + ga*p[1]*B,
        -ga*p[1]*A + m*(om0^2-p[1]^2)*B - F0,
    ];
    parameters = [p]
)

System of length 2
 2 variables: A, B
 1 parameters: p

 A*(9.86960440108936 - p^2) + 0.1*B*p
 -1.0 - 0.1*A*p + B*(9.86960440108936 - p^2)

In [69]:
# define sytem - version 2 
# p declared as a vector - second component not used 
@var A B p[1:2]

m=1; freq = .5; om0=2*π*freq; ga=0.1; F0 = 1.;

F = System(
    [
        m*(om0^2-p[1]^2)*A + ga*p[1]*B,
        -ga*p[1]*A + m*(om0^2-p[1]^2)*B - F0,
    ];
    parameters = p
)

System of length 2
 2 variables: A, B
 2 parameters: p₁, p₂

 A*(9.86960440108936 - p₁^2) + 0.1*B*p₁
 -1.0 - 0.1*A*p₁ + B*(9.86960440108936 - p₁^2)

In [77]:
# solve system 
freq = .55; omd=2*π*freq; 
p = [omd, 0.] 
# Compute all solutions for F_p
results_p = solve(F, target_parameters = p)

Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0xf7bc3056
• start_system: :polyhedral


In [78]:
real_solutions(results_p)

1-element Vector{Vector{Float64}}:
 [-0.0782700846804151, -0.46943156214406473]

In [74]:
# generate some random data to simulate the parameters
data = [[d,0.] for d in Vector(0:1.:10.)] 

# track p towards the entries of data
data_points = solve(
    F,
    solutions(result_p);
    start_parameters =  p,
    target_parameters = data
)

11-element Vector{Tuple{Result, Vector{Float64}}}:
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [0.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [1.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [2.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [3.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [4.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [5.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [6.0, 0.0])
 (Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x9dfe25f1
, [7.0, 0.0])
 (Result with

In [42]:
real_solutions(data_points[1])

LoadError: MethodError: no method matching real_solutions(::Tuple{Result, Vector{Float64}})
Closest candidates are:
  real_solutions(::Union{Result, AbstractVector{<:PathResult}}; tol, kwargs...) at ~/.julia/packages/HomotopyContinuation/I1faM/src/result.jl:308

In [24]:
typeof(data_points)

Vector{Tuple{Result, Vector{Float64}}} (alias for Array{Tuple{Result, Array{Float64, 1}}, 1})

In [27]:
d = data_points[1]
typeof(d)

Tuple{Result, Vector{Float64}}

In [46]:
d.Result

LoadError: type Tuple has no field Result

In [28]:
d = data_points[1]

(Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x27829e44
, [0.0, 0.0])

In [53]:
keys(d)

Base.OneTo(2)

In [52]:
d[1]

Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x27829e44


In [64]:
d[2]

2-element Vector{Float64}:
 0.0
 0.0

In [39]:
values(d)

(Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x27829e44
, [0.0, 0.0])

In [35]:
collect(d)

2-element Vector{Any}:
 Result with 1 solution
• 1 path tracked
• 1 non-singular solution (1 real)
• random_seed: 0x27829e44

 [0.0, 0.0]

In [67]:
res = [d[2] for d in data_points] 

11-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [1.0, 0.0]
 [2.0, 0.0]
 [3.0, 0.0]
 [4.0, 0.0]
 [5.0, 0.0]
 [6.0, 0.0]
 [7.0, 0.0]
 [8.0, 0.0]
 [9.0, 0.0]
 [10.0, 0.0]

## Section 4: Non-Linear Harmonic Oscillator - Duffing - Single Harmonic  

In [9]:
function  duffing_hb_singlemode(x,p)
    A, B = x 
    omd = p 
    m=1; freq = .5; om0=2*π*freq; ga=0.1; stiffnlin=10.; F0 = 1.; 
    mismathvec = zeros(eltype(x),2)
    mismathvec[1] = m*(om0^2-omd^2)*A + ga*omd*B + stiffnlin*.75*(A^3 + A*B^2) 
    mismathvec[2] = -ga*omd*A + m*(om0^2-omd^2)*B + stiffnlin*.75*(B^3 + A^2*B) - F0 
    return mismathvec 
end 

duffing_hb_singlemode (generic function with 1 method)

In [42]:
# define sytem 
@var A B p

m=1; freq = .5; om0=2*π*freq; ga=0.1; stiffnlin=10.; F0 = 1.;

F = System(
    [
        m*(om0^2-p[1]^2)*A + ga*p[1]*B + stiffnlin*.75*(A^3 + A*B^2),
        -ga*p[1]*A + m*(om0^2-p[1]^2)*B + + stiffnlin*.75*(B^3 + A^2*B) - F0,
    ];
    parameters = [p]
)

System of length 2
 2 variables: A, B
 1 parameters: p

 A*(9.86960440108936 - p^2) + 0.1*B*p + 7.5*(A*B^2 + A^3)
 -1.0 - 0.1*A*p + B*(9.86960440108936 - p^2) + 7.5*(A^2*B + B^3)

In [43]:
# solve system 
p = [0.1] 
# Compute all solutions for F_p
result_p = solve(F, target_parameters = p)

Tracking 9 paths... 100%|███████████████████████████████| Time: 0:00:01
  # paths tracked:                  9
  # non-singular solutions (real):  3 (1)
  # singular endpoints (real):      0 (0)
  # total solutions (real):         3 (1)


Result with 3 solutions
• 9 paths tracked
• 3 non-singular solutions (1 real)
• random_seed: 0x52f6a4fc
• start_system: :polyhedral
